### ISSUE TITLE
Using utility functions

### ISSUE THREAD

**Issue by Moult** [tudelft3d/GeorefIFC#2]
G'day! I had a peek through the code and notice a number of places which might benefit from util functions, and a number of places which might benefit from adding a util function upstream to IfcOpenShell :)

Have you seen https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.8.0/src/ifcopenshell-python/ifcopenshell/util/geolocation.py ? In particular there are quite a few goodies in the latest version.

Some you might enjoy:

 - [get_true_north](https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.8.0/src/ifcopenshell-python/ifcopenshell/util/geolocation.py#L600)
 - [get_helmert_transformation_parameters](https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.8.0/src/ifcopenshell-python/ifcopenshell/util/geolocation.py#L600)
 - [auto_local2global](https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.8.0/src/ifcopenshell-python/ifcopenshell/util/geolocation.py#L600) or [auto_xyz2enh](https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.8.0/src/ifcopenshell-python/ifcopenshell/util/geolocation.py#L129)

These take into account the IFC2X3 fallback, as well as the new coordinate operations in IFC4X3. They also handle a few more situations that might be problematic (e.g. I saw a few instances of by_type("IfcGeometricRepresentationContext")[0] which might get a subcontext or non-Model/Plan context).

**Comment by amiroo4** [comment]
Hi Dion,

Thanks for recommending the libraries. I'll take a look at them.
