### ISSUE TITLE
Handling Z coordinate?

### ISSUE THREAD

**Issue by nataschake** [tudelft3d/GeorefIFC#5]
Hi, 
does this tool allow for conversion of Z coordinate (= height) of a building/building element?

**Comment by amiroo4** [comment]
Hi,
Yes, it does, but keep in mind that the visualization component displays your model according to the local BIM Z elevation on the map.

**Comment by nataschake** [comment]
> Hi, Yes, it does, but keep in mind that the visualization component displays your model according to the local BIM Z elevation on the map.

Thanks @amiroo4!
Am I right in saying that "Local BIM Z elevation" is always related to "Ground floor floor height (EFH)" (I use XPlanung terminology, in particular `xplan:hoehenbezug` values). So in fact Z value remains the same without any calculations of "the height above sea"?
Or the tool is aware of e.g., standard elevation zero (NHN), or similar (Source: https://www.crs-geo.eu/crs-national.htm)?

**Comment by amiroo4** [comment]
The tool is aware of Z calculation based on epsg code that is shared and consider for calculation of OrtogonalHeight. But since it's using 2d global maptiler service for visualization , it is rendered based on local BIM Z elevation.
